In [1]:
import numpy as np
data = np.random.randn(2,3)
data

array([[ 0.25105539, -0.44968435,  0.49740907],
       [ 0.00415715, -0.49646219, -0.35729261]])

In [2]:
data*10

array([[ 2.51055386, -4.49684347,  4.97409072],
       [ 0.04157147, -4.96462192, -3.57292607]])

In [3]:
data + data

array([[ 0.50211077, -0.89936869,  0.99481814],
       [ 0.00831429, -0.99292438, -0.71458521]])

In [4]:
data.shape

(2, 3)

In [5]:
data.dtype

dtype('float64')

In [22]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [23]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
arr2.ndim

2

In [25]:
arr2.shape

(2, 4)

In [26]:
arr1.dtype

dtype('float64')

In [27]:
arr2.dtype

dtype('int32')

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [31]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [32]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [33]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('float64')

In [34]:
arr2.dtype

dtype('int32')

In [35]:
arr = np.array([1, 2, 3, 4, 5])

In [36]:
arr.dtype

dtype('int32')

In [37]:
float_arr = arr.astype(np.float64)

In [38]:
float_arr.dtype

dtype('float64')

In [39]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
int_arr = arr.astype(np.int32)
int_arr 

array([ 3, -1, -2,  0, 12, 10])

In [43]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
arr4 = numeric_strings.astype(float)

In [44]:
arr4.dtype

dtype('float64')

In [45]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [46]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [47]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [48]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
1/ arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [51]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [52]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [53]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [54]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr[5]

5

In [56]:
arr[5:8]

array([5, 6, 7])

In [58]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [59]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [60]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [61]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [62]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
arr2d[2]

array([7, 8, 9])

In [64]:
arr2d[0][2]

3

In [65]:
arr2d[0, 2]

3

In [66]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [67]:
arr3d.shape

(2, 2, 3)

In [68]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
arr3d[0].shape

(2, 3)

In [71]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [73]:
arr3d[1, 0]

array([7, 8, 9])

In [74]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [75]:
x[0]

array([7, 8, 9])

In [76]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [77]:
arr2d[:2] 

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [86]:
ex = arr2d[1, :2]
ex.shape

(2,)

In [81]:
arr2d[:2, 2]

array([3, 6])

In [82]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [83]:
arr2d[:2, 1:] = 0

In [84]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

# boolean indexing

In [2]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [3]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [4]:
data

array([[-0.4593    , -0.82055152, -0.90370693,  1.13882783],
       [-1.0909358 , -2.616684  , -0.50456344, -1.3626194 ],
       [ 1.78970489,  1.69927513,  2.37860947, -0.80112255],
       [-0.52789127, -0.07073788,  0.74344786, -2.16440252],
       [ 1.0291443 ,  0.14419012, -0.98607026, -0.16623984],
       [ 1.8140079 ,  0.76753116,  1.71575737,  0.94011244],
       [-0.92024829,  0.51845809,  0.57829169,  0.29609768]])

In [5]:
names == 'Bob' 

array([ True, False, False,  True, False, False, False])

In [6]:
data[names == 'Bob']

array([[-0.4593    , -0.82055152, -0.90370693,  1.13882783],
       [-0.52789127, -0.07073788,  0.74344786, -2.16440252]])

In [7]:
data[names == 'Bob', 2:]

array([[-0.90370693,  1.13882783],
       [ 0.74344786, -2.16440252]])

In [8]:
data[names == 'Bob', 3]

array([ 1.13882783, -2.16440252])

In [9]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [10]:
~(names == 'Bob')

array([False,  True,  True, False,  True,  True,  True])

In [11]:
data[~(names == 'Bob')]

array([[-1.0909358 , -2.616684  , -0.50456344, -1.3626194 ],
       [ 1.78970489,  1.69927513,  2.37860947, -0.80112255],
       [ 1.0291443 ,  0.14419012, -0.98607026, -0.16623984],
       [ 1.8140079 ,  0.76753116,  1.71575737,  0.94011244],
       [-0.92024829,  0.51845809,  0.57829169,  0.29609768]])

In [12]:
mask = (names == 'Bob') | (names == 'Will')

In [13]:
mask 

array([ True, False,  True,  True,  True, False, False])

In [14]:
data[mask]

array([[-0.4593    , -0.82055152, -0.90370693,  1.13882783],
       [ 1.78970489,  1.69927513,  2.37860947, -0.80112255],
       [-0.52789127, -0.07073788,  0.74344786, -2.16440252],
       [ 1.0291443 ,  0.14419012, -0.98607026, -0.16623984]])

In [15]:
data[data < 0] = 0

In [16]:
data

array([[0.        , 0.        , 0.        , 1.13882783],
       [0.        , 0.        , 0.        , 0.        ],
       [1.78970489, 1.69927513, 2.37860947, 0.        ],
       [0.        , 0.        , 0.74344786, 0.        ],
       [1.0291443 , 0.14419012, 0.        , 0.        ],
       [1.8140079 , 0.76753116, 1.71575737, 0.94011244],
       [0.        , 0.51845809, 0.57829169, 0.29609768]])

In [17]:
data[names != 'Joe'] = 7

In [18]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.8140079 , 0.76753116, 1.71575737, 0.94011244],
       [0.        , 0.51845809, 0.57829169, 0.29609768]])

In [19]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [21]:
arr.reshape((4, 2)) 

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [22]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [23]:
arr = np.arange(15)

In [24]:
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
arr = np.arange(15)
other_arr = np.ones((3, 5))

In [27]:
other_arr.shape

(3, 5)

In [33]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [34]:
arr.ravel()
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [37]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [38]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [40]:
arr = np.arange(32).reshape((8, 4))

In [41]:
ar1 = arr[[1, 5, 7, 2], [0, 3, 1, 2]]

In [42]:
ar1

array([ 4, 23, 29, 10])

In [43]:
ar1[0] = 10

In [44]:
ar1

array([10, 23, 29, 10])

In [45]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [46]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [47]:
arr[[1, 5, 7, 2],:]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [48]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [50]:
arr = np.random.randn(6, 3) 

In [51]:
np.dot(arr.T, arr)

array([[ 1.582433  ,  0.4779039 , -0.08880975],
       [ 0.4779039 ,  6.32216557, -2.62394108],
       [-0.08880975, -2.62394108,  1.23247688]])

In [52]:
arr = np.arange(16).reshape((2, 2, 4))

In [53]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [55]:
ar1 = arr.transpose((1, 0, 2))

In [56]:
ar1[0] = 3

In [57]:
arr

array([[[ 3,  3,  3,  3],
        [ 4,  5,  6,  7]],

       [[ 3,  3,  3,  3],
        [12, 13, 14, 15]]])

In [58]:
arr.swapaxes(1, 2) 

array([[[ 3,  4],
        [ 3,  5],
        [ 3,  6],
        [ 3,  7]],

       [[ 3, 12],
        [ 3, 13],
        [ 3, 14],
        [ 3, 15]]])

In [60]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [62]:
x = np.random.randn(8)
y = np.random.randn(8)

In [63]:
np.maximum(x, y)

array([1.82193981, 0.6099738 , 1.13036223, 1.09076184, 1.3942625 ,
       0.36126755, 1.00333903, 0.79511278])

In [64]:
arr = np.random.randn(7) * 5
arr

array([-6.5020287 ,  1.09210619, -2.00050205,  7.33104425, -1.66357827,
       -1.74680185, -3.03063383])

In [66]:
remainder, whole_part = np.modf(arr)
remainder

array([-0.74438534,  0.12400055,  0.54355642,  0.9161318 ,  0.19341215,
        0.5925348 , -0.38896454])

In [67]:
whole_part

array([-0.,  0.,  6.,  5.,  7.,  5., -0.])

In [68]:
np.sqrt(arr)
np.sqrt(arr, arr)
arr

C:\Users\Ubicomp_Lab\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.
C:\Users\Ubicomp_Lab\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


array([       nan, 0.35213712, 2.55803761, 2.43230997, 2.68205372,
       2.36485408,        nan])

In [69]:
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points
xs, ys = np.meshgrid(points,points)
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [70]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [71]:
z = np.sqrt(xs**2 + ys**2)
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [72]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [73]:
result = [(x if c else y) for x,y,c in zip(xarr, yarr,cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [74]:
result = np.where(cond, xarr,yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [75]:
arr = np.random.randn(4, 4)
arr

array([[-0.04563866,  0.87031236,  0.93690956,  0.22976607],
       [-0.71177771, -0.46046569, -0.7579177 , -0.12679455],
       [ 0.29160279, -1.48340077, -1.5314457 ,  0.33090777],
       [-0.43525274, -0.74411685,  0.16769336,  0.81288366]])

In [77]:
np.where(arr>0 , 2,-2)

array([[-2,  2,  2,  2],
       [-2, -2, -2, -2],
       [ 2, -2, -2,  2],
       [-2, -2,  2,  2]])

In [78]:
np.where(arr > 0, 2, arr)

array([[-0.04563866,  2.        ,  2.        ,  2.        ],
       [-0.71177771, -0.46046569, -0.7579177 , -0.12679455],
       [ 2.        , -1.48340077, -1.5314457 ,  2.        ],
       [-0.43525274, -0.74411685,  2.        ,  2.        ]])

In [79]:
arr = np.random.randn(5, 4)
arr

array([[-2.06778533,  0.85217939, -0.34505151, -1.78938891],
       [-1.06320794, -0.85710958, -1.1637328 , -0.94386382],
       [ 1.29002115,  0.03259072,  0.17613345,  1.57889557],
       [ 0.12109765,  1.04554821, -0.3244147 ,  2.06921068],
       [ 0.01728934,  0.52778753,  0.06527202, -1.37163698]])

In [80]:
arr.mean()

-0.10750829261618007

In [81]:
np.mean(arr)

-0.10750829261618007

In [82]:
arr.sum()

-2.1501658523236014

In [83]:
arr.mean(axis=1)

array([-0.83751159, -1.00697853,  0.76941022,  0.72786046, -0.19032202])

In [84]:
arr.sum(axis=0)

array([-1.70258512,  1.60099626, -1.59179353, -0.45678346])

In [85]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])

In [86]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [87]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [88]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [89]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [90]:
arr = np.random.randn(100)
(arr>0).sum()

53

In [91]:
bools = np.array([False, False, True, False])

In [92]:
bools.any()

True

In [93]:
bools.all()

False

In [94]:
arr = np.random.randn(6)
arr.sort()

In [95]:
arr = np.random.randn(5, 3)

In [96]:
arr.sort(1)

In [97]:
large_arr = np.random.randn(1000)
large_arr.sort()

In [98]:
large_arr[int(0.05*len(large_arr))]

-1.6944805935228795

In [99]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [100]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [101]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [102]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [103]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [104]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [105]:
x.dot(y) 

array([[ 28.,  64.],
       [ 67., 181.]])

In [107]:
np.dot(x,y) 

array([[ 28.,  64.],
       [ 67., 181.]])

In [108]:
np.dot(x, np.ones(3)) 

array([ 6., 15.])

In [109]:
np.dot(x, [[1], [1], [1]])

array([[ 6.],
       [15.]])

In [110]:
x @ np.ones(3)

array([ 6., 15.])

In [111]:
from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
mat = X.T.dot(X)

In [112]:
mat

array([[ 4.24364686,  0.44501338,  0.87178516, -3.26858205,  0.72442429],
       [ 0.44501338,  3.42467864,  0.27218009, -2.72719463,  0.19112388],
       [ 0.87178516,  0.27218009,  1.69406413, -1.10043316,  0.26506642],
       [-3.26858205, -2.72719463, -1.10043316,  4.61082069,  0.08397606],
       [ 0.72442429,  0.19112388,  0.26506642,  0.08397606,  2.16969527]])

In [113]:
inv(mat)

array([[ 6.88226468,  6.52923611,  1.97840486,  9.27612686, -3.47373848],
       [ 6.52923611,  6.79525784,  2.05383408,  9.19960896, -3.385555  ],
       [ 1.97840486,  2.05383408,  1.33819305,  2.95703958, -1.1194069 ],
       [ 9.27612686,  9.19960896,  2.95703958, 13.02669272, -4.77295544],
       [-3.47373848, -3.385555  , -1.1194069 , -4.77295544,  2.24043081]])

In [114]:
mat.dot(inv(mat)) 

array([[ 1.00000000e+00, -1.97154056e-15,  3.06676669e-16,
        -2.23794619e-16, -1.16519725e-15],
       [ 2.36269397e-15,  1.00000000e+00,  4.33269770e-16,
        -1.57318993e-15, -2.38942382e-16],
       [-8.84228031e-16,  4.16691776e-16,  1.00000000e+00,
        -9.93909149e-16, -3.22118023e-17],
       [ 7.33542994e-15, -3.49827824e-15, -9.46389476e-17,
         1.00000000e+00,  2.72278602e-16],
       [-8.37360610e-16,  9.30829106e-16,  2.43207527e-17,
         2.57325655e-15,  1.00000000e+00]])

In [116]:
q, r = qr(mat)
r

array([[-5.49317796, -2.31237807, -1.65412604,  5.65313905, -0.85335517],
       [ 0.        , -3.75866589, -0.26817151,  2.81488303,  0.19649421],
       [ 0.        ,  0.        , -1.47550299,  0.27228583, -0.17380001],
       [ 0.        ,  0.        ,  0.        , -0.8020004 , -2.12841712],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.13790474]])

In [117]:
samples = np.random.normal(size=(4, 4))
samples

array([[-1.01173216,  0.45065437,  0.64278104, -0.22637949],
       [-0.68601254, -1.6749459 ,  0.72972175,  0.06834179],
       [-1.82446508, -1.1308907 ,  0.66171529, -0.16899022],
       [ 0.20089877, -0.9946348 , -0.12461967, -0.46858895]])

In [118]:
from random import normalvariate
N = 1000000

In [122]:
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

813 ms ± 20.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [121]:
%timeit np.random.normal(size=N)

28.1 ms ± 579 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [123]:
np.random.seed(1234)
samples

[0.5390084583344272,
 0.6025564792486616,
 -0.04542981561916759,
 0.0315966750319683,
 -2.7761747357526723,
 0.6862470854898112,
 -0.6985300414247746,
 -1.793741944733337,
 0.1425493213523013,
 1.3722798156382843,
 -1.7856310327119842,
 -0.8220729410391111,
 0.47063963888003796,
 -0.3080126245450172,
 1.1728401448700114,
 1.4498447824578724,
 -1.2334136373887665,
 -1.6019437528988985,
 0.44468145674681425,
 0.8542403180880019,
 0.22538590910943032,
 0.2080878135786697,
 0.7720962638680052,
 0.6226327563416401,
 -0.3648800579164605,
 1.3671331726803206,
 -0.6375532639453947,
 0.6073888045664174,
 0.2580250594084715,
 -0.1159196177807212,
 -1.4180143185784198,
 0.5840601062858531,
 -1.2264433768353076,
 0.3959669949452337,
 -0.8861429900421666,
 -1.7864428878934524,
 0.06771607099237614,
 1.057512793908847,
 -0.6177152847543642,
 1.5077106663500714,
 -0.003314312527526324,
 0.22375533282540172,
 0.13937097551086422,
 -1.7115504485703168,
 -0.41100832994461944,
 0.28545547289292406,
 1.89

In [124]:
rng = np.random.RandomState(1234)

In [125]:
rng.randn(10) 

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

In [127]:
import random
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0, 1) else -1
    position += step
walk.append(position)

In [128]:
plt.figure()
plt.plot(walk[:100])

NameError: name 'plt' is not defined

In [129]:
np.random.seed(12345)
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()

In [130]:
plt.figure()
plt.plot(walk[:100])

NameError: name 'plt' is not defined

In [131]:
walk.min()

-3

In [132]:
walk.max()

31

In [133]:
(np.abs(walk)>=10).argmax()

37

In [134]:
np.where(np.abs(walk)>=10)[0][0]
np.nonzero(np.abs(walk)>=10)[0][0]

37

In [139]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps)) 
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(1)

In [140]:
walks

array([[  1,   0,  -1, ..., -16, -17, -16],
       [ -1,   0,  -1, ...,  -6,  -7,  -6],
       [  1,   2,   3, ...,  46,  45,  46],
       ...,
       [  1,   0,  -1, ..., -30, -31, -30],
       [ -1,   0,   1, ..., -44, -43, -44],
       [  1,   0,   1, ..., -48, -49, -48]], dtype=int32)

In [141]:
walks.min()
walks.max()

111

In [142]:
hits30 = (np.abs(walks) >= 30).any(1)
hits30

array([False, False,  True, ...,  True,  True,  True])

In [143]:
hits30.sum() # Number that hit 30 or -30

3340

In [144]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)

In [145]:
crossing_times.mean() 

510.64610778443114

In [147]:
steps = np.random.normal(loc=0, scale=0.25, size=(nwalks, nsteps))